### ISSUE TITLE
ImportError: No module named umonitor - Ubuntu 18.04

### ISSUE THREAD

**Issue by mikehlim** [rliou92/python-umonitor#1]
Hello rliou92,

I have finished "sudo python setup.py", but execution threw an error below. I'm running Ubuntu 18.04. Any insight would be greatly appreciated.
=================================================
mlim@linux:~/python-umonitor$ umonitor
Traceback (most recent call last):
  File "/usr/local/bin/umonitor", line 11, in <module>
    load_entry_point('umonitor==20181018', 'console_scripts', 'umonitor')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/umonitor-20181018-py2.7-linux-x86_64.egg/umonitor/__init__.py", line 3, in <module>
    from umonitor.umonitor import Umonitor
ImportError: No module named umonitor

**Comment by rliou92** [comment]
Did you run `python setup.py install`?

**Comment by mikehlim** [comment]
Yes, but I didn't see any errors though.

mlim@linux:~/python-umonitor$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing umonitor.egg-info/PKG-INFO
writing top-level names to umonitor.egg-info/top_level.txt
writing dependency_links to umonitor.egg-info/dependency_links.txt
writing entry points to umonitor.egg-info/entry_points.txt
reading manifest file 'umonitor.egg-info/SOURCES.txt'
writing manifest file 'umonitor.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/screen.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/umonitor
copying build/lib.linux-x86_64-2.7/umonitor/umonitor.py -> build/bdist.linux-x86_64/egg/umonitor
copying build/lib.linux-x86_64-2.7/umonitor/__init__.py -> build/bdist.linux-x86_64/egg/umonitor
byte-compiling build/bdist.linux-x86_64/egg/umonitor/umonitor.py to umonitor.pyc
byte-compiling build/bdist.linux-x86_64/egg/umonitor/__init__.py to __init__.pyc
creating stub loader for screen.so
byte-compiling build/bdist.linux-x86_64/egg/screen.py to screen.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying umonitor.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umonitor.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umonitor.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umonitor.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umonitor.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umonitor.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/umonitor-20181018-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing umonitor-20181018-py2.7-linux-x86_64.egg
removing '/usr/local/lib/python2.7/dist-packages/umonitor-20181018-py2.7-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/umonitor-20181018-py2.7-linux-x86_64.egg
Extracting umonitor-20181018-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
umonitor 20181018 is already the active version in easy-install.pth
Installing umonitor script to /usr/local/bin
